# Generated by Django 4.2.1 on 2023-05-28 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OptionVote', to='polls.question'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tags', to='polls.question'),
        ),
    ]
